function [pos_hip,pos_thigh,pos_calf,pos_feet,Jaco] = autoGen_go1Kinematics(q_hip,q_thigh,q_calf,leg_offset_x,leg_offset_y,thigh_y,thigh_length,calf_length)
%AUTOGEN_GO1KINEMATICS
%    [POS_HIP,POS_THIGH,POS_CALF,POS_FEET,JACO] = AUTOGEN_GO1KINEMATICS(Q_HIP,Q_THIGH,Q_CALF,LEG_OFFSET_X,LEG_OFFSET_Y,THIGH_Y,THIGH_LENGTH,CALF_LENGTH)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Apr-2022 14:23:34

pos_hip = [leg_offset_x;leg_offset_y;0.0];
if nargout > 1
    t2 = cos(q_hip);
    t3 = t2.*thigh_y;
    t4 = sin(q_hip);
    t5 = t4.*thigh_y;
    pos_thigh = [leg_offset_x;leg_offset_y+t3;t5];
end
if nargout > 2
    t6 = cos(q_thigh);
    t7 = sin(q_thigh);
    t8 = t7.*thigh_length;
    t9 = sin(q_calf);
    t10 = cos(q_calf);
    t11 = t2.*t6.*thigh_length;
    pos_calf = [leg_offset_x+t8;leg_offset_y+t3-t4.*t6.*thigh_length;t5+t11];
end
if nargout > 3
    t12 = t6.*t10;
    t13 = t12-t7.*t9;
    t14 = calf_length.*t13;
    t15 = t2.*t6.*t10;
    t16 = t15-t2.*t7.*t9;
    t17 = calf_length.*t16;
    t18 = t4.*t7.*t10;
    t19 = t4.*t6.*t9;
    t20 = t18+t19;
    t21 = calf_length.*t20;
    t22 = t4.*t6.*t10;
    t23 = t22-t4.*t7.*t9;
    pos_feet = [leg_offset_x+t8+calf_length.*(t6.*t9+t7.*t10);leg_offset_y+t3-calf_length.*t23-t4.*t6.*thigh_length;t5+t11+t17];
end
if nargout > 4
    t24 = t2.*t7.*t10;
    t25 = t2.*t6.*t9;
    t26 = t24+t25;
    Jaco = reshape([0.0,-t5-t11-t17,t3-calf_length.*t23-t4.*t6.*thigh_length,t14+t6.*thigh_length,t21+t4.*t7.*thigh_length,-calf_length.*t26-t2.*t7.*thigh_length,t14,t21,-calf_length.*t26],[3,3]);
end
