
/*
Auto-generated by CVXPYgen on January 26, 2024 at 00:02:18.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.X_ref) {
        for(i=0; i<120; i++) {
            cpg_update_X_ref(i, CPG_Params_cpp.X_ref[i]);
        }
    }
    if (CPG_Updated_cpp.R) {
        for(i=0; i<36; i++) {
            cpg_update_R(i, CPG_Params_cpp.R[i]);
        }
    }
    if (CPG_Updated_cpp.R_grf) {
        for(i=0; i<144; i++) {
            cpg_update_R_grf(i, CPG_Params_cpp.R_grf[i]);
        }
    }
    if (CPG_Updated_cpp.x_init) {
        for(i=0; i<12; i++) {
            cpg_update_x_init(i, CPG_Params_cpp.x_init[i]);
        }
    }
    if (CPG_Updated_cpp.A) {
        for(i=0; i<720; i++) {
            cpg_update_A(i, CPG_Params_cpp.A[i]);
        }
    }
    if (CPG_Updated_cpp.no_contact) {
        for(i=0; i<40; i++) {
            cpg_update_no_contact(i, CPG_Params_cpp.no_contact[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<132; i++) {
        CPG_Prim_cpp.X[i] = CPG_Prim.X[i];
    }
    for(i=0; i<60; i++) {
        CPG_Prim_cpp.U[i] = CPG_Prim.U[i];
    }
    for(i=0; i<120; i++) {
        CPG_Prim_cpp.F[i] = CPG_Prim.F[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<12; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<120; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d3[i] = CPG_Dual.d3[i];
    }
    CPG_Dual_cpp.d4 = CPG_Dual.d4;
    CPG_Dual_cpp.d5 = CPG_Dual.d5;
    CPG_Dual_cpp.d6 = CPG_Dual.d6;
    CPG_Dual_cpp.d7 = CPG_Dual.d7;
    CPG_Dual_cpp.d8 = CPG_Dual.d8;
    CPG_Dual_cpp.d9 = CPG_Dual.d9;
    CPG_Dual_cpp.d10 = CPG_Dual.d10;
    CPG_Dual_cpp.d11 = CPG_Dual.d11;
    CPG_Dual_cpp.d12 = CPG_Dual.d12;
    CPG_Dual_cpp.d13 = CPG_Dual.d13;
    CPG_Dual_cpp.d14 = CPG_Dual.d14;
    CPG_Dual_cpp.d15 = CPG_Dual.d15;
    CPG_Dual_cpp.d16 = CPG_Dual.d16;
    CPG_Dual_cpp.d17 = CPG_Dual.d17;
    CPG_Dual_cpp.d18 = CPG_Dual.d18;
    CPG_Dual_cpp.d19 = CPG_Dual.d19;
    CPG_Dual_cpp.d20 = CPG_Dual.d20;
    CPG_Dual_cpp.d21 = CPG_Dual.d21;
    CPG_Dual_cpp.d22 = CPG_Dual.d22;
    CPG_Dual_cpp.d23 = CPG_Dual.d23;
    CPG_Dual_cpp.d24 = CPG_Dual.d24;
    CPG_Dual_cpp.d25 = CPG_Dual.d25;
    CPG_Dual_cpp.d26 = CPG_Dual.d26;
    CPG_Dual_cpp.d27 = CPG_Dual.d27;
    CPG_Dual_cpp.d28 = CPG_Dual.d28;
    CPG_Dual_cpp.d29 = CPG_Dual.d29;
    CPG_Dual_cpp.d30 = CPG_Dual.d30;
    CPG_Dual_cpp.d31 = CPG_Dual.d31;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d32[i] = CPG_Dual.d32[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d33[i] = CPG_Dual.d33[i];
    }
    CPG_Dual_cpp.d34 = CPG_Dual.d34;
    CPG_Dual_cpp.d35 = CPG_Dual.d35;
    CPG_Dual_cpp.d36 = CPG_Dual.d36;
    CPG_Dual_cpp.d37 = CPG_Dual.d37;
    CPG_Dual_cpp.d38 = CPG_Dual.d38;
    CPG_Dual_cpp.d39 = CPG_Dual.d39;
    CPG_Dual_cpp.d40 = CPG_Dual.d40;
    CPG_Dual_cpp.d41 = CPG_Dual.d41;
    CPG_Dual_cpp.d42 = CPG_Dual.d42;
    CPG_Dual_cpp.d43 = CPG_Dual.d43;
    CPG_Dual_cpp.d44 = CPG_Dual.d44;
    CPG_Dual_cpp.d45 = CPG_Dual.d45;
    CPG_Dual_cpp.d46 = CPG_Dual.d46;
    CPG_Dual_cpp.d47 = CPG_Dual.d47;
    CPG_Dual_cpp.d48 = CPG_Dual.d48;
    CPG_Dual_cpp.d49 = CPG_Dual.d49;
    CPG_Dual_cpp.d50 = CPG_Dual.d50;
    CPG_Dual_cpp.d51 = CPG_Dual.d51;
    CPG_Dual_cpp.d52 = CPG_Dual.d52;
    CPG_Dual_cpp.d53 = CPG_Dual.d53;
    CPG_Dual_cpp.d54 = CPG_Dual.d54;
    CPG_Dual_cpp.d55 = CPG_Dual.d55;
    CPG_Dual_cpp.d56 = CPG_Dual.d56;
    CPG_Dual_cpp.d57 = CPG_Dual.d57;
    CPG_Dual_cpp.d58 = CPG_Dual.d58;
    CPG_Dual_cpp.d59 = CPG_Dual.d59;
    CPG_Dual_cpp.d60 = CPG_Dual.d60;
    CPG_Dual_cpp.d61 = CPG_Dual.d61;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d62[i] = CPG_Dual.d62[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d63[i] = CPG_Dual.d63[i];
    }
    CPG_Dual_cpp.d64 = CPG_Dual.d64;
    CPG_Dual_cpp.d65 = CPG_Dual.d65;
    CPG_Dual_cpp.d66 = CPG_Dual.d66;
    CPG_Dual_cpp.d67 = CPG_Dual.d67;
    CPG_Dual_cpp.d68 = CPG_Dual.d68;
    CPG_Dual_cpp.d69 = CPG_Dual.d69;
    CPG_Dual_cpp.d70 = CPG_Dual.d70;
    CPG_Dual_cpp.d71 = CPG_Dual.d71;
    CPG_Dual_cpp.d72 = CPG_Dual.d72;
    CPG_Dual_cpp.d73 = CPG_Dual.d73;
    CPG_Dual_cpp.d74 = CPG_Dual.d74;
    CPG_Dual_cpp.d75 = CPG_Dual.d75;
    CPG_Dual_cpp.d76 = CPG_Dual.d76;
    CPG_Dual_cpp.d77 = CPG_Dual.d77;
    CPG_Dual_cpp.d78 = CPG_Dual.d78;
    CPG_Dual_cpp.d79 = CPG_Dual.d79;
    CPG_Dual_cpp.d80 = CPG_Dual.d80;
    CPG_Dual_cpp.d81 = CPG_Dual.d81;
    CPG_Dual_cpp.d82 = CPG_Dual.d82;
    CPG_Dual_cpp.d83 = CPG_Dual.d83;
    CPG_Dual_cpp.d84 = CPG_Dual.d84;
    CPG_Dual_cpp.d85 = CPG_Dual.d85;
    CPG_Dual_cpp.d86 = CPG_Dual.d86;
    CPG_Dual_cpp.d87 = CPG_Dual.d87;
    CPG_Dual_cpp.d88 = CPG_Dual.d88;
    CPG_Dual_cpp.d89 = CPG_Dual.d89;
    CPG_Dual_cpp.d90 = CPG_Dual.d90;
    CPG_Dual_cpp.d91 = CPG_Dual.d91;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d92[i] = CPG_Dual.d92[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d93[i] = CPG_Dual.d93[i];
    }
    CPG_Dual_cpp.d94 = CPG_Dual.d94;
    CPG_Dual_cpp.d95 = CPG_Dual.d95;
    CPG_Dual_cpp.d96 = CPG_Dual.d96;
    CPG_Dual_cpp.d97 = CPG_Dual.d97;
    CPG_Dual_cpp.d98 = CPG_Dual.d98;
    CPG_Dual_cpp.d99 = CPG_Dual.d99;
    CPG_Dual_cpp.d100 = CPG_Dual.d100;
    CPG_Dual_cpp.d101 = CPG_Dual.d101;
    CPG_Dual_cpp.d102 = CPG_Dual.d102;
    CPG_Dual_cpp.d103 = CPG_Dual.d103;
    CPG_Dual_cpp.d104 = CPG_Dual.d104;
    CPG_Dual_cpp.d105 = CPG_Dual.d105;
    CPG_Dual_cpp.d106 = CPG_Dual.d106;
    CPG_Dual_cpp.d107 = CPG_Dual.d107;
    CPG_Dual_cpp.d108 = CPG_Dual.d108;
    CPG_Dual_cpp.d109 = CPG_Dual.d109;
    CPG_Dual_cpp.d110 = CPG_Dual.d110;
    CPG_Dual_cpp.d111 = CPG_Dual.d111;
    CPG_Dual_cpp.d112 = CPG_Dual.d112;
    CPG_Dual_cpp.d113 = CPG_Dual.d113;
    CPG_Dual_cpp.d114 = CPG_Dual.d114;
    CPG_Dual_cpp.d115 = CPG_Dual.d115;
    CPG_Dual_cpp.d116 = CPG_Dual.d116;
    CPG_Dual_cpp.d117 = CPG_Dual.d117;
    CPG_Dual_cpp.d118 = CPG_Dual.d118;
    CPG_Dual_cpp.d119 = CPG_Dual.d119;
    CPG_Dual_cpp.d120 = CPG_Dual.d120;
    CPG_Dual_cpp.d121 = CPG_Dual.d121;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d122[i] = CPG_Dual.d122[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d123[i] = CPG_Dual.d123[i];
    }
    CPG_Dual_cpp.d124 = CPG_Dual.d124;
    CPG_Dual_cpp.d125 = CPG_Dual.d125;
    CPG_Dual_cpp.d126 = CPG_Dual.d126;
    CPG_Dual_cpp.d127 = CPG_Dual.d127;
    CPG_Dual_cpp.d128 = CPG_Dual.d128;
    CPG_Dual_cpp.d129 = CPG_Dual.d129;
    CPG_Dual_cpp.d130 = CPG_Dual.d130;
    CPG_Dual_cpp.d131 = CPG_Dual.d131;
    CPG_Dual_cpp.d132 = CPG_Dual.d132;
    CPG_Dual_cpp.d133 = CPG_Dual.d133;
    CPG_Dual_cpp.d134 = CPG_Dual.d134;
    CPG_Dual_cpp.d135 = CPG_Dual.d135;
    CPG_Dual_cpp.d136 = CPG_Dual.d136;
    CPG_Dual_cpp.d137 = CPG_Dual.d137;
    CPG_Dual_cpp.d138 = CPG_Dual.d138;
    CPG_Dual_cpp.d139 = CPG_Dual.d139;
    CPG_Dual_cpp.d140 = CPG_Dual.d140;
    CPG_Dual_cpp.d141 = CPG_Dual.d141;
    CPG_Dual_cpp.d142 = CPG_Dual.d142;
    CPG_Dual_cpp.d143 = CPG_Dual.d143;
    CPG_Dual_cpp.d144 = CPG_Dual.d144;
    CPG_Dual_cpp.d145 = CPG_Dual.d145;
    CPG_Dual_cpp.d146 = CPG_Dual.d146;
    CPG_Dual_cpp.d147 = CPG_Dual.d147;
    CPG_Dual_cpp.d148 = CPG_Dual.d148;
    CPG_Dual_cpp.d149 = CPG_Dual.d149;
    CPG_Dual_cpp.d150 = CPG_Dual.d150;
    CPG_Dual_cpp.d151 = CPG_Dual.d151;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d152[i] = CPG_Dual.d152[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d153[i] = CPG_Dual.d153[i];
    }
    CPG_Dual_cpp.d154 = CPG_Dual.d154;
    CPG_Dual_cpp.d155 = CPG_Dual.d155;
    CPG_Dual_cpp.d156 = CPG_Dual.d156;
    CPG_Dual_cpp.d157 = CPG_Dual.d157;
    CPG_Dual_cpp.d158 = CPG_Dual.d158;
    CPG_Dual_cpp.d159 = CPG_Dual.d159;
    CPG_Dual_cpp.d160 = CPG_Dual.d160;
    CPG_Dual_cpp.d161 = CPG_Dual.d161;
    CPG_Dual_cpp.d162 = CPG_Dual.d162;
    CPG_Dual_cpp.d163 = CPG_Dual.d163;
    CPG_Dual_cpp.d164 = CPG_Dual.d164;
    CPG_Dual_cpp.d165 = CPG_Dual.d165;
    CPG_Dual_cpp.d166 = CPG_Dual.d166;
    CPG_Dual_cpp.d167 = CPG_Dual.d167;
    CPG_Dual_cpp.d168 = CPG_Dual.d168;
    CPG_Dual_cpp.d169 = CPG_Dual.d169;
    CPG_Dual_cpp.d170 = CPG_Dual.d170;
    CPG_Dual_cpp.d171 = CPG_Dual.d171;
    CPG_Dual_cpp.d172 = CPG_Dual.d172;
    CPG_Dual_cpp.d173 = CPG_Dual.d173;
    CPG_Dual_cpp.d174 = CPG_Dual.d174;
    CPG_Dual_cpp.d175 = CPG_Dual.d175;
    CPG_Dual_cpp.d176 = CPG_Dual.d176;
    CPG_Dual_cpp.d177 = CPG_Dual.d177;
    CPG_Dual_cpp.d178 = CPG_Dual.d178;
    CPG_Dual_cpp.d179 = CPG_Dual.d179;
    CPG_Dual_cpp.d180 = CPG_Dual.d180;
    CPG_Dual_cpp.d181 = CPG_Dual.d181;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d182[i] = CPG_Dual.d182[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d183[i] = CPG_Dual.d183[i];
    }
    CPG_Dual_cpp.d184 = CPG_Dual.d184;
    CPG_Dual_cpp.d185 = CPG_Dual.d185;
    CPG_Dual_cpp.d186 = CPG_Dual.d186;
    CPG_Dual_cpp.d187 = CPG_Dual.d187;
    CPG_Dual_cpp.d188 = CPG_Dual.d188;
    CPG_Dual_cpp.d189 = CPG_Dual.d189;
    CPG_Dual_cpp.d190 = CPG_Dual.d190;
    CPG_Dual_cpp.d191 = CPG_Dual.d191;
    CPG_Dual_cpp.d192 = CPG_Dual.d192;
    CPG_Dual_cpp.d193 = CPG_Dual.d193;
    CPG_Dual_cpp.d194 = CPG_Dual.d194;
    CPG_Dual_cpp.d195 = CPG_Dual.d195;
    CPG_Dual_cpp.d196 = CPG_Dual.d196;
    CPG_Dual_cpp.d197 = CPG_Dual.d197;
    CPG_Dual_cpp.d198 = CPG_Dual.d198;
    CPG_Dual_cpp.d199 = CPG_Dual.d199;
    CPG_Dual_cpp.d200 = CPG_Dual.d200;
    CPG_Dual_cpp.d201 = CPG_Dual.d201;
    CPG_Dual_cpp.d202 = CPG_Dual.d202;
    CPG_Dual_cpp.d203 = CPG_Dual.d203;
    CPG_Dual_cpp.d204 = CPG_Dual.d204;
    CPG_Dual_cpp.d205 = CPG_Dual.d205;
    CPG_Dual_cpp.d206 = CPG_Dual.d206;
    CPG_Dual_cpp.d207 = CPG_Dual.d207;
    CPG_Dual_cpp.d208 = CPG_Dual.d208;
    CPG_Dual_cpp.d209 = CPG_Dual.d209;
    CPG_Dual_cpp.d210 = CPG_Dual.d210;
    CPG_Dual_cpp.d211 = CPG_Dual.d211;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d212[i] = CPG_Dual.d212[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d213[i] = CPG_Dual.d213[i];
    }
    CPG_Dual_cpp.d214 = CPG_Dual.d214;
    CPG_Dual_cpp.d215 = CPG_Dual.d215;
    CPG_Dual_cpp.d216 = CPG_Dual.d216;
    CPG_Dual_cpp.d217 = CPG_Dual.d217;
    CPG_Dual_cpp.d218 = CPG_Dual.d218;
    CPG_Dual_cpp.d219 = CPG_Dual.d219;
    CPG_Dual_cpp.d220 = CPG_Dual.d220;
    CPG_Dual_cpp.d221 = CPG_Dual.d221;
    CPG_Dual_cpp.d222 = CPG_Dual.d222;
    CPG_Dual_cpp.d223 = CPG_Dual.d223;
    CPG_Dual_cpp.d224 = CPG_Dual.d224;
    CPG_Dual_cpp.d225 = CPG_Dual.d225;
    CPG_Dual_cpp.d226 = CPG_Dual.d226;
    CPG_Dual_cpp.d227 = CPG_Dual.d227;
    CPG_Dual_cpp.d228 = CPG_Dual.d228;
    CPG_Dual_cpp.d229 = CPG_Dual.d229;
    CPG_Dual_cpp.d230 = CPG_Dual.d230;
    CPG_Dual_cpp.d231 = CPG_Dual.d231;
    CPG_Dual_cpp.d232 = CPG_Dual.d232;
    CPG_Dual_cpp.d233 = CPG_Dual.d233;
    CPG_Dual_cpp.d234 = CPG_Dual.d234;
    CPG_Dual_cpp.d235 = CPG_Dual.d235;
    CPG_Dual_cpp.d236 = CPG_Dual.d236;
    CPG_Dual_cpp.d237 = CPG_Dual.d237;
    CPG_Dual_cpp.d238 = CPG_Dual.d238;
    CPG_Dual_cpp.d239 = CPG_Dual.d239;
    CPG_Dual_cpp.d240 = CPG_Dual.d240;
    CPG_Dual_cpp.d241 = CPG_Dual.d241;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d242[i] = CPG_Dual.d242[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d243[i] = CPG_Dual.d243[i];
    }
    CPG_Dual_cpp.d244 = CPG_Dual.d244;
    CPG_Dual_cpp.d245 = CPG_Dual.d245;
    CPG_Dual_cpp.d246 = CPG_Dual.d246;
    CPG_Dual_cpp.d247 = CPG_Dual.d247;
    CPG_Dual_cpp.d248 = CPG_Dual.d248;
    CPG_Dual_cpp.d249 = CPG_Dual.d249;
    CPG_Dual_cpp.d250 = CPG_Dual.d250;
    CPG_Dual_cpp.d251 = CPG_Dual.d251;
    CPG_Dual_cpp.d252 = CPG_Dual.d252;
    CPG_Dual_cpp.d253 = CPG_Dual.d253;
    CPG_Dual_cpp.d254 = CPG_Dual.d254;
    CPG_Dual_cpp.d255 = CPG_Dual.d255;
    CPG_Dual_cpp.d256 = CPG_Dual.d256;
    CPG_Dual_cpp.d257 = CPG_Dual.d257;
    CPG_Dual_cpp.d258 = CPG_Dual.d258;
    CPG_Dual_cpp.d259 = CPG_Dual.d259;
    CPG_Dual_cpp.d260 = CPG_Dual.d260;
    CPG_Dual_cpp.d261 = CPG_Dual.d261;
    CPG_Dual_cpp.d262 = CPG_Dual.d262;
    CPG_Dual_cpp.d263 = CPG_Dual.d263;
    CPG_Dual_cpp.d264 = CPG_Dual.d264;
    CPG_Dual_cpp.d265 = CPG_Dual.d265;
    CPG_Dual_cpp.d266 = CPG_Dual.d266;
    CPG_Dual_cpp.d267 = CPG_Dual.d267;
    CPG_Dual_cpp.d268 = CPG_Dual.d268;
    CPG_Dual_cpp.d269 = CPG_Dual.d269;
    CPG_Dual_cpp.d270 = CPG_Dual.d270;
    CPG_Dual_cpp.d271 = CPG_Dual.d271;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d272[i] = CPG_Dual.d272[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d273[i] = CPG_Dual.d273[i];
    }
    CPG_Dual_cpp.d274 = CPG_Dual.d274;
    CPG_Dual_cpp.d275 = CPG_Dual.d275;
    CPG_Dual_cpp.d276 = CPG_Dual.d276;
    CPG_Dual_cpp.d277 = CPG_Dual.d277;
    CPG_Dual_cpp.d278 = CPG_Dual.d278;
    CPG_Dual_cpp.d279 = CPG_Dual.d279;
    CPG_Dual_cpp.d280 = CPG_Dual.d280;
    CPG_Dual_cpp.d281 = CPG_Dual.d281;
    CPG_Dual_cpp.d282 = CPG_Dual.d282;
    CPG_Dual_cpp.d283 = CPG_Dual.d283;
    CPG_Dual_cpp.d284 = CPG_Dual.d284;
    CPG_Dual_cpp.d285 = CPG_Dual.d285;
    CPG_Dual_cpp.d286 = CPG_Dual.d286;
    CPG_Dual_cpp.d287 = CPG_Dual.d287;
    CPG_Dual_cpp.d288 = CPG_Dual.d288;
    CPG_Dual_cpp.d289 = CPG_Dual.d289;
    CPG_Dual_cpp.d290 = CPG_Dual.d290;
    CPG_Dual_cpp.d291 = CPG_Dual.d291;
    CPG_Dual_cpp.d292 = CPG_Dual.d292;
    CPG_Dual_cpp.d293 = CPG_Dual.d293;
    CPG_Dual_cpp.d294 = CPG_Dual.d294;
    CPG_Dual_cpp.d295 = CPG_Dual.d295;
    CPG_Dual_cpp.d296 = CPG_Dual.d296;
    CPG_Dual_cpp.d297 = CPG_Dual.d297;
    CPG_Dual_cpp.d298 = CPG_Dual.d298;
    CPG_Dual_cpp.d299 = CPG_Dual.d299;
    CPG_Dual_cpp.d300 = CPG_Dual.d300;
    CPG_Dual_cpp.d301 = CPG_Dual.d301;
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0*(ASA_end-ASA_start) / CLOCKS_PER_SEC;
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("X_ref", &CPG_Params_cpp_t::X_ref)
            .def_readwrite("R", &CPG_Params_cpp_t::R)
            .def_readwrite("R_grf", &CPG_Params_cpp_t::R_grf)
            .def_readwrite("x_init", &CPG_Params_cpp_t::x_init)
            .def_readwrite("A", &CPG_Params_cpp_t::A)
            .def_readwrite("no_contact", &CPG_Params_cpp_t::no_contact)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("X_ref", &CPG_Updated_cpp_t::X_ref)
            .def_readwrite("R", &CPG_Updated_cpp_t::R)
            .def_readwrite("R_grf", &CPG_Updated_cpp_t::R_grf)
            .def_readwrite("x_init", &CPG_Updated_cpp_t::x_init)
            .def_readwrite("A", &CPG_Updated_cpp_t::A)
            .def_readwrite("no_contact", &CPG_Updated_cpp_t::no_contact)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("X", &CPG_Prim_cpp_t::X)
            .def_readwrite("U", &CPG_Prim_cpp_t::U)
            .def_readwrite("F", &CPG_Prim_cpp_t::F)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &CPG_Dual_cpp_t::d93)
            .def_readwrite("d94", &CPG_Dual_cpp_t::d94)
            .def_readwrite("d95", &CPG_Dual_cpp_t::d95)
            .def_readwrite("d96", &CPG_Dual_cpp_t::d96)
            .def_readwrite("d97", &CPG_Dual_cpp_t::d97)
            .def_readwrite("d98", &CPG_Dual_cpp_t::d98)
            .def_readwrite("d99", &CPG_Dual_cpp_t::d99)
            .def_readwrite("d100", &CPG_Dual_cpp_t::d100)
            .def_readwrite("d101", &CPG_Dual_cpp_t::d101)
            .def_readwrite("d102", &CPG_Dual_cpp_t::d102)
            .def_readwrite("d103", &CPG_Dual_cpp_t::d103)
            .def_readwrite("d104", &CPG_Dual_cpp_t::d104)
            .def_readwrite("d105", &CPG_Dual_cpp_t::d105)
            .def_readwrite("d106", &CPG_Dual_cpp_t::d106)
            .def_readwrite("d107", &CPG_Dual_cpp_t::d107)
            .def_readwrite("d108", &CPG_Dual_cpp_t::d108)
            .def_readwrite("d109", &CPG_Dual_cpp_t::d109)
            .def_readwrite("d110", &CPG_Dual_cpp_t::d110)
            .def_readwrite("d111", &CPG_Dual_cpp_t::d111)
            .def_readwrite("d112", &CPG_Dual_cpp_t::d112)
            .def_readwrite("d113", &CPG_Dual_cpp_t::d113)
            .def_readwrite("d114", &CPG_Dual_cpp_t::d114)
            .def_readwrite("d115", &CPG_Dual_cpp_t::d115)
            .def_readwrite("d116", &CPG_Dual_cpp_t::d116)
            .def_readwrite("d117", &CPG_Dual_cpp_t::d117)
            .def_readwrite("d118", &CPG_Dual_cpp_t::d118)
            .def_readwrite("d119", &CPG_Dual_cpp_t::d119)
            .def_readwrite("d120", &CPG_Dual_cpp_t::d120)
            .def_readwrite("d121", &CPG_Dual_cpp_t::d121)
            .def_readwrite("d122", &CPG_Dual_cpp_t::d122)
            .def_readwrite("d123", &CPG_Dual_cpp_t::d123)
            .def_readwrite("d124", &CPG_Dual_cpp_t::d124)
            .def_readwrite("d125", &CPG_Dual_cpp_t::d125)
            .def_readwrite("d126", &CPG_Dual_cpp_t::d126)
            .def_readwrite("d127", &CPG_Dual_cpp_t::d127)
            .def_readwrite("d128", &CPG_Dual_cpp_t::d128)
            .def_readwrite("d129", &CPG_Dual_cpp_t::d129)
            .def_readwrite("d130", &CPG_Dual_cpp_t::d130)
            .def_readwrite("d131", &CPG_Dual_cpp_t::d131)
            .def_readwrite("d132", &CPG_Dual_cpp_t::d132)
            .def_readwrite("d133", &CPG_Dual_cpp_t::d133)
            .def_readwrite("d134", &CPG_Dual_cpp_t::d134)
            .def_readwrite("d135", &CPG_Dual_cpp_t::d135)
            .def_readwrite("d136", &CPG_Dual_cpp_t::d136)
            .def_readwrite("d137", &CPG_Dual_cpp_t::d137)
            .def_readwrite("d138", &CPG_Dual_cpp_t::d138)
            .def_readwrite("d139", &CPG_Dual_cpp_t::d139)
            .def_readwrite("d140", &CPG_Dual_cpp_t::d140)
            .def_readwrite("d141", &CPG_Dual_cpp_t::d141)
            .def_readwrite("d142", &CPG_Dual_cpp_t::d142)
            .def_readwrite("d143", &CPG_Dual_cpp_t::d143)
            .def_readwrite("d144", &CPG_Dual_cpp_t::d144)
            .def_readwrite("d145", &CPG_Dual_cpp_t::d145)
            .def_readwrite("d146", &CPG_Dual_cpp_t::d146)
            .def_readwrite("d147", &CPG_Dual_cpp_t::d147)
            .def_readwrite("d148", &CPG_Dual_cpp_t::d148)
            .def_readwrite("d149", &CPG_Dual_cpp_t::d149)
            .def_readwrite("d150", &CPG_Dual_cpp_t::d150)
            .def_readwrite("d151", &CPG_Dual_cpp_t::d151)
            .def_readwrite("d152", &CPG_Dual_cpp_t::d152)
            .def_readwrite("d153", &CPG_Dual_cpp_t::d153)
            .def_readwrite("d154", &CPG_Dual_cpp_t::d154)
            .def_readwrite("d155", &CPG_Dual_cpp_t::d155)
            .def_readwrite("d156", &CPG_Dual_cpp_t::d156)
            .def_readwrite("d157", &CPG_Dual_cpp_t::d157)
            .def_readwrite("d158", &CPG_Dual_cpp_t::d158)
            .def_readwrite("d159", &CPG_Dual_cpp_t::d159)
            .def_readwrite("d160", &CPG_Dual_cpp_t::d160)
            .def_readwrite("d161", &CPG_Dual_cpp_t::d161)
            .def_readwrite("d162", &CPG_Dual_cpp_t::d162)
            .def_readwrite("d163", &CPG_Dual_cpp_t::d163)
            .def_readwrite("d164", &CPG_Dual_cpp_t::d164)
            .def_readwrite("d165", &CPG_Dual_cpp_t::d165)
            .def_readwrite("d166", &CPG_Dual_cpp_t::d166)
            .def_readwrite("d167", &CPG_Dual_cpp_t::d167)
            .def_readwrite("d168", &CPG_Dual_cpp_t::d168)
            .def_readwrite("d169", &CPG_Dual_cpp_t::d169)
            .def_readwrite("d170", &CPG_Dual_cpp_t::d170)
            .def_readwrite("d171", &CPG_Dual_cpp_t::d171)
            .def_readwrite("d172", &CPG_Dual_cpp_t::d172)
            .def_readwrite("d173", &CPG_Dual_cpp_t::d173)
            .def_readwrite("d174", &CPG_Dual_cpp_t::d174)
            .def_readwrite("d175", &CPG_Dual_cpp_t::d175)
            .def_readwrite("d176", &CPG_Dual_cpp_t::d176)
            .def_readwrite("d177", &CPG_Dual_cpp_t::d177)
            .def_readwrite("d178", &CPG_Dual_cpp_t::d178)
            .def_readwrite("d179", &CPG_Dual_cpp_t::d179)
            .def_readwrite("d180", &CPG_Dual_cpp_t::d180)
            .def_readwrite("d181", &CPG_Dual_cpp_t::d181)
            .def_readwrite("d182", &CPG_Dual_cpp_t::d182)
            .def_readwrite("d183", &CPG_Dual_cpp_t::d183)
            .def_readwrite("d184", &CPG_Dual_cpp_t::d184)
            .def_readwrite("d185", &CPG_Dual_cpp_t::d185)
            .def_readwrite("d186", &CPG_Dual_cpp_t::d186)
            .def_readwrite("d187", &CPG_Dual_cpp_t::d187)
            .def_readwrite("d188", &CPG_Dual_cpp_t::d188)
            .def_readwrite("d189", &CPG_Dual_cpp_t::d189)
            .def_readwrite("d190", &CPG_Dual_cpp_t::d190)
            .def_readwrite("d191", &CPG_Dual_cpp_t::d191)
            .def_readwrite("d192", &CPG_Dual_cpp_t::d192)
            .def_readwrite("d193", &CPG_Dual_cpp_t::d193)
            .def_readwrite("d194", &CPG_Dual_cpp_t::d194)
            .def_readwrite("d195", &CPG_Dual_cpp_t::d195)
            .def_readwrite("d196", &CPG_Dual_cpp_t::d196)
            .def_readwrite("d197", &CPG_Dual_cpp_t::d197)
            .def_readwrite("d198", &CPG_Dual_cpp_t::d198)
            .def_readwrite("d199", &CPG_Dual_cpp_t::d199)
            .def_readwrite("d200", &CPG_Dual_cpp_t::d200)
            .def_readwrite("d201", &CPG_Dual_cpp_t::d201)
            .def_readwrite("d202", &CPG_Dual_cpp_t::d202)
            .def_readwrite("d203", &CPG_Dual_cpp_t::d203)
            .def_readwrite("d204", &CPG_Dual_cpp_t::d204)
            .def_readwrite("d205", &CPG_Dual_cpp_t::d205)
            .def_readwrite("d206", &CPG_Dual_cpp_t::d206)
            .def_readwrite("d207", &CPG_Dual_cpp_t::d207)
            .def_readwrite("d208", &CPG_Dual_cpp_t::d208)
            .def_readwrite("d209", &CPG_Dual_cpp_t::d209)
            .def_readwrite("d210", &CPG_Dual_cpp_t::d210)
            .def_readwrite("d211", &CPG_Dual_cpp_t::d211)
            .def_readwrite("d212", &CPG_Dual_cpp_t::d212)
            .def_readwrite("d213", &CPG_Dual_cpp_t::d213)
            .def_readwrite("d214", &CPG_Dual_cpp_t::d214)
            .def_readwrite("d215", &CPG_Dual_cpp_t::d215)
            .def_readwrite("d216", &CPG_Dual_cpp_t::d216)
            .def_readwrite("d217", &CPG_Dual_cpp_t::d217)
            .def_readwrite("d218", &CPG_Dual_cpp_t::d218)
            .def_readwrite("d219", &CPG_Dual_cpp_t::d219)
            .def_readwrite("d220", &CPG_Dual_cpp_t::d220)
            .def_readwrite("d221", &CPG_Dual_cpp_t::d221)
            .def_readwrite("d222", &CPG_Dual_cpp_t::d222)
            .def_readwrite("d223", &CPG_Dual_cpp_t::d223)
            .def_readwrite("d224", &CPG_Dual_cpp_t::d224)
            .def_readwrite("d225", &CPG_Dual_cpp_t::d225)
            .def_readwrite("d226", &CPG_Dual_cpp_t::d226)
            .def_readwrite("d227", &CPG_Dual_cpp_t::d227)
            .def_readwrite("d228", &CPG_Dual_cpp_t::d228)
            .def_readwrite("d229", &CPG_Dual_cpp_t::d229)
            .def_readwrite("d230", &CPG_Dual_cpp_t::d230)
            .def_readwrite("d231", &CPG_Dual_cpp_t::d231)
            .def_readwrite("d232", &CPG_Dual_cpp_t::d232)
            .def_readwrite("d233", &CPG_Dual_cpp_t::d233)
            .def_readwrite("d234", &CPG_Dual_cpp_t::d234)
            .def_readwrite("d235", &CPG_Dual_cpp_t::d235)
            .def_readwrite("d236", &CPG_Dual_cpp_t::d236)
            .def_readwrite("d237", &CPG_Dual_cpp_t::d237)
            .def_readwrite("d238", &CPG_Dual_cpp_t::d238)
            .def_readwrite("d239", &CPG_Dual_cpp_t::d239)
            .def_readwrite("d240", &CPG_Dual_cpp_t::d240)
            .def_readwrite("d241", &CPG_Dual_cpp_t::d241)
            .def_readwrite("d242", &CPG_Dual_cpp_t::d242)
            .def_readwrite("d243", &CPG_Dual_cpp_t::d243)
            .def_readwrite("d244", &CPG_Dual_cpp_t::d244)
            .def_readwrite("d245", &CPG_Dual_cpp_t::d245)
            .def_readwrite("d246", &CPG_Dual_cpp_t::d246)
            .def_readwrite("d247", &CPG_Dual_cpp_t::d247)
            .def_readwrite("d248", &CPG_Dual_cpp_t::d248)
            .def_readwrite("d249", &CPG_Dual_cpp_t::d249)
            .def_readwrite("d250", &CPG_Dual_cpp_t::d250)
            .def_readwrite("d251", &CPG_Dual_cpp_t::d251)
            .def_readwrite("d252", &CPG_Dual_cpp_t::d252)
            .def_readwrite("d253", &CPG_Dual_cpp_t::d253)
            .def_readwrite("d254", &CPG_Dual_cpp_t::d254)
            .def_readwrite("d255", &CPG_Dual_cpp_t::d255)
            .def_readwrite("d256", &CPG_Dual_cpp_t::d256)
            .def_readwrite("d257", &CPG_Dual_cpp_t::d257)
            .def_readwrite("d258", &CPG_Dual_cpp_t::d258)
            .def_readwrite("d259", &CPG_Dual_cpp_t::d259)
            .def_readwrite("d260", &CPG_Dual_cpp_t::d260)
            .def_readwrite("d261", &CPG_Dual_cpp_t::d261)
            .def_readwrite("d262", &CPG_Dual_cpp_t::d262)
            .def_readwrite("d263", &CPG_Dual_cpp_t::d263)
            .def_readwrite("d264", &CPG_Dual_cpp_t::d264)
            .def_readwrite("d265", &CPG_Dual_cpp_t::d265)
            .def_readwrite("d266", &CPG_Dual_cpp_t::d266)
            .def_readwrite("d267", &CPG_Dual_cpp_t::d267)
            .def_readwrite("d268", &CPG_Dual_cpp_t::d268)
            .def_readwrite("d269", &CPG_Dual_cpp_t::d269)
            .def_readwrite("d270", &CPG_Dual_cpp_t::d270)
            .def_readwrite("d271", &CPG_Dual_cpp_t::d271)
            .def_readwrite("d272", &CPG_Dual_cpp_t::d272)
            .def_readwrite("d273", &CPG_Dual_cpp_t::d273)
            .def_readwrite("d274", &CPG_Dual_cpp_t::d274)
            .def_readwrite("d275", &CPG_Dual_cpp_t::d275)
            .def_readwrite("d276", &CPG_Dual_cpp_t::d276)
            .def_readwrite("d277", &CPG_Dual_cpp_t::d277)
            .def_readwrite("d278", &CPG_Dual_cpp_t::d278)
            .def_readwrite("d279", &CPG_Dual_cpp_t::d279)
            .def_readwrite("d280", &CPG_Dual_cpp_t::d280)
            .def_readwrite("d281", &CPG_Dual_cpp_t::d281)
            .def_readwrite("d282", &CPG_Dual_cpp_t::d282)
            .def_readwrite("d283", &CPG_Dual_cpp_t::d283)
            .def_readwrite("d284", &CPG_Dual_cpp_t::d284)
            .def_readwrite("d285", &CPG_Dual_cpp_t::d285)
            .def_readwrite("d286", &CPG_Dual_cpp_t::d286)
            .def_readwrite("d287", &CPG_Dual_cpp_t::d287)
            .def_readwrite("d288", &CPG_Dual_cpp_t::d288)
            .def_readwrite("d289", &CPG_Dual_cpp_t::d289)
            .def_readwrite("d290", &CPG_Dual_cpp_t::d290)
            .def_readwrite("d291", &CPG_Dual_cpp_t::d291)
            .def_readwrite("d292", &CPG_Dual_cpp_t::d292)
            .def_readwrite("d293", &CPG_Dual_cpp_t::d293)
            .def_readwrite("d294", &CPG_Dual_cpp_t::d294)
            .def_readwrite("d295", &CPG_Dual_cpp_t::d295)
            .def_readwrite("d296", &CPG_Dual_cpp_t::d296)
            .def_readwrite("d297", &CPG_Dual_cpp_t::d297)
            .def_readwrite("d298", &CPG_Dual_cpp_t::d298)
            .def_readwrite("d299", &CPG_Dual_cpp_t::d299)
            .def_readwrite("d300", &CPG_Dual_cpp_t::d300)
            .def_readwrite("d301", &CPG_Dual_cpp_t::d301)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_rho", &cpg_set_solver_rho);
    m.def("set_solver_max_iter", &cpg_set_solver_max_iter);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_prim_inf", &cpg_set_solver_eps_prim_inf);
    m.def("set_solver_eps_dual_inf", &cpg_set_solver_eps_dual_inf);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_scaled_termination", &cpg_set_solver_scaled_termination);
    m.def("set_solver_check_termination", &cpg_set_solver_check_termination);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);

}
