#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on February 01, 2024 at 16:52:29.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[612];
extern c_float ldata[772];
extern c_float udata[772];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[612];
extern c_float Dinvscaling[612];
extern c_float Escaling[772];
extern c_float Einvscaling[772];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[1384];
extern c_int linsys_solver_P[1384];
extern c_float linsys_solver_bp[1384];
extern c_float linsys_solver_sol[1384];
extern c_float linsys_solver_rho_inv_vec[772];
extern c_int linsys_solver_Pdiag_idx[300];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[300];
extern c_int linsys_solver_AtoKKT[3872];
extern c_int linsys_solver_rhotoKKT[772];
extern QDLDL_float linsys_solver_D[1384];
extern QDLDL_int linsys_solver_etree[1384];
extern QDLDL_int linsys_solver_Lnz[1384];
extern QDLDL_int   linsys_solver_iwork[4152];
extern QDLDL_bool  linsys_solver_bwork[1384];
extern QDLDL_float linsys_solver_fwork[1384];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[612];
extern c_float ysolution[772];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[772];
extern c_float work_rho_inv_vec[772];
extern c_int work_constr_type[772];
extern c_float work_x[612];
extern c_float work_y[772];
extern c_float work_z[772];
extern c_float work_xz_tilde[1384];
extern c_float work_x_prev[612];
extern c_float work_z_prev[772];
extern c_float work_Ax[772];
extern c_float work_Px[612];
extern c_float work_Aty[612];
extern c_float work_delta_y[772];
extern c_float work_Atdelta_y[612];
extern c_float work_delta_x[612];
extern c_float work_Pdelta_x[612];
extern c_float work_Adelta_x[772];
extern c_float work_D_temp[612];
extern c_float work_D_temp_A[612];
extern c_float work_E_temp[772];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
