
/*
Auto-generated by CVXPYgen on January 26, 2024 at 00:02:18.
Content: Function declarations.
*/

#include "types.h"

// Update user-defined parameter values
extern void cpg_update_X_ref(c_int idx, c_float val);
extern void cpg_update_R(c_int idx, c_float val);
extern void cpg_update_R_grf(c_int idx, c_float val);
extern void cpg_update_x_init(c_int idx, c_float val);
extern void cpg_update_A(c_int idx, c_float val);
extern void cpg_update_no_contact(c_int idx, c_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_A();
extern void cpg_canonicalize_l();
extern void cpg_canonicalize_u();

// Retrieve dual solution in terms of user-defined constraints
extern void cpg_retrieve_dual();

// Retrieve solver information
extern void cpg_retrieve_info();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_rho(c_float rho_new);
extern void cpg_set_solver_max_iter(c_int max_iter_new);
extern void cpg_set_solver_eps_abs(c_float eps_abs_new);
extern void cpg_set_solver_eps_rel(c_float eps_rel_new);
extern void cpg_set_solver_eps_prim_inf(c_float eps_prim_inf_new);
extern void cpg_set_solver_eps_dual_inf(c_float eps_dual_inf_new);
extern void cpg_set_solver_alpha(c_float alpha_new);
extern void cpg_set_solver_scaled_termination(c_int scaled_termination_new);
extern void cpg_set_solver_check_termination(c_int check_termination_new);
extern void cpg_set_solver_warm_start(c_int warm_start_new);
