
/*
Auto-generated by CVXPYgen on January 26, 2024 at 00:02:18.
Content: Type definitions and variable declarations.
*/

#include "types.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

// Canonical parameters
typedef struct {
  csc        *P;         // Canonical parameter P
  c_float    *q;         // Canonical parameter q
  c_float    d;          // Canonical parameter d
  csc        *A;         // Canonical parameter A
  c_float    *l;         // Canonical parameter l
  c_float    *u;         // Canonical parameter u
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        P;          // Bool, if canonical parameter P outdated
  int        q;          // Bool, if canonical parameter q outdated
  int        d;          // Bool, if canonical parameter d outdated
  int        A;          // Bool, if canonical parameter A outdated
  int        l;          // Bool, if canonical parameter l outdated
  int        u;          // Bool, if canonical parameter u outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  c_float    *X;         // Your variable X
  c_float    *U;         // Your variable U
  c_float    *F;         // Your variable F
} CPG_Prim_t;

// Dual solution
typedef struct {
  c_float    *d0;        // Your dual variable for constraint d0
  c_float    *d1;        // Your dual variable for constraint d1
  c_float    *d2;        // Your dual variable for constraint d2
  c_float    *d3;        // Your dual variable for constraint d3
  c_float    d4;         // Your dual variable for constraint d4
  c_float    d5;         // Your dual variable for constraint d5
  c_float    d6;         // Your dual variable for constraint d6
  c_float    d7;         // Your dual variable for constraint d7
  c_float    d8;         // Your dual variable for constraint d8
  c_float    d9;         // Your dual variable for constraint d9
  c_float    d10;        // Your dual variable for constraint d10
  c_float    d11;        // Your dual variable for constraint d11
  c_float    d12;        // Your dual variable for constraint d12
  c_float    d13;        // Your dual variable for constraint d13
  c_float    d14;        // Your dual variable for constraint d14
  c_float    d15;        // Your dual variable for constraint d15
  c_float    d16;        // Your dual variable for constraint d16
  c_float    d17;        // Your dual variable for constraint d17
  c_float    d18;        // Your dual variable for constraint d18
  c_float    d19;        // Your dual variable for constraint d19
  c_float    d20;        // Your dual variable for constraint d20
  c_float    d21;        // Your dual variable for constraint d21
  c_float    d22;        // Your dual variable for constraint d22
  c_float    d23;        // Your dual variable for constraint d23
  c_float    d24;        // Your dual variable for constraint d24
  c_float    d25;        // Your dual variable for constraint d25
  c_float    d26;        // Your dual variable for constraint d26
  c_float    d27;        // Your dual variable for constraint d27
  c_float    d28;        // Your dual variable for constraint d28
  c_float    d29;        // Your dual variable for constraint d29
  c_float    d30;        // Your dual variable for constraint d30
  c_float    d31;        // Your dual variable for constraint d31
  c_float    *d32;       // Your dual variable for constraint d32
  c_float    *d33;       // Your dual variable for constraint d33
  c_float    d34;        // Your dual variable for constraint d34
  c_float    d35;        // Your dual variable for constraint d35
  c_float    d36;        // Your dual variable for constraint d36
  c_float    d37;        // Your dual variable for constraint d37
  c_float    d38;        // Your dual variable for constraint d38
  c_float    d39;        // Your dual variable for constraint d39
  c_float    d40;        // Your dual variable for constraint d40
  c_float    d41;        // Your dual variable for constraint d41
  c_float    d42;        // Your dual variable for constraint d42
  c_float    d43;        // Your dual variable for constraint d43
  c_float    d44;        // Your dual variable for constraint d44
  c_float    d45;        // Your dual variable for constraint d45
  c_float    d46;        // Your dual variable for constraint d46
  c_float    d47;        // Your dual variable for constraint d47
  c_float    d48;        // Your dual variable for constraint d48
  c_float    d49;        // Your dual variable for constraint d49
  c_float    d50;        // Your dual variable for constraint d50
  c_float    d51;        // Your dual variable for constraint d51
  c_float    d52;        // Your dual variable for constraint d52
  c_float    d53;        // Your dual variable for constraint d53
  c_float    d54;        // Your dual variable for constraint d54
  c_float    d55;        // Your dual variable for constraint d55
  c_float    d56;        // Your dual variable for constraint d56
  c_float    d57;        // Your dual variable for constraint d57
  c_float    d58;        // Your dual variable for constraint d58
  c_float    d59;        // Your dual variable for constraint d59
  c_float    d60;        // Your dual variable for constraint d60
  c_float    d61;        // Your dual variable for constraint d61
  c_float    *d62;       // Your dual variable for constraint d62
  c_float    *d63;       // Your dual variable for constraint d63
  c_float    d64;        // Your dual variable for constraint d64
  c_float    d65;        // Your dual variable for constraint d65
  c_float    d66;        // Your dual variable for constraint d66
  c_float    d67;        // Your dual variable for constraint d67
  c_float    d68;        // Your dual variable for constraint d68
  c_float    d69;        // Your dual variable for constraint d69
  c_float    d70;        // Your dual variable for constraint d70
  c_float    d71;        // Your dual variable for constraint d71
  c_float    d72;        // Your dual variable for constraint d72
  c_float    d73;        // Your dual variable for constraint d73
  c_float    d74;        // Your dual variable for constraint d74
  c_float    d75;        // Your dual variable for constraint d75
  c_float    d76;        // Your dual variable for constraint d76
  c_float    d77;        // Your dual variable for constraint d77
  c_float    d78;        // Your dual variable for constraint d78
  c_float    d79;        // Your dual variable for constraint d79
  c_float    d80;        // Your dual variable for constraint d80
  c_float    d81;        // Your dual variable for constraint d81
  c_float    d82;        // Your dual variable for constraint d82
  c_float    d83;        // Your dual variable for constraint d83
  c_float    d84;        // Your dual variable for constraint d84
  c_float    d85;        // Your dual variable for constraint d85
  c_float    d86;        // Your dual variable for constraint d86
  c_float    d87;        // Your dual variable for constraint d87
  c_float    d88;        // Your dual variable for constraint d88
  c_float    d89;        // Your dual variable for constraint d89
  c_float    d90;        // Your dual variable for constraint d90
  c_float    d91;        // Your dual variable for constraint d91
  c_float    *d92;       // Your dual variable for constraint d92
  c_float    *d93;       // Your dual variable for constraint d93
  c_float    d94;        // Your dual variable for constraint d94
  c_float    d95;        // Your dual variable for constraint d95
  c_float    d96;        // Your dual variable for constraint d96
  c_float    d97;        // Your dual variable for constraint d97
  c_float    d98;        // Your dual variable for constraint d98
  c_float    d99;        // Your dual variable for constraint d99
  c_float    d100;       // Your dual variable for constraint d100
  c_float    d101;       // Your dual variable for constraint d101
  c_float    d102;       // Your dual variable for constraint d102
  c_float    d103;       // Your dual variable for constraint d103
  c_float    d104;       // Your dual variable for constraint d104
  c_float    d105;       // Your dual variable for constraint d105
  c_float    d106;       // Your dual variable for constraint d106
  c_float    d107;       // Your dual variable for constraint d107
  c_float    d108;       // Your dual variable for constraint d108
  c_float    d109;       // Your dual variable for constraint d109
  c_float    d110;       // Your dual variable for constraint d110
  c_float    d111;       // Your dual variable for constraint d111
  c_float    d112;       // Your dual variable for constraint d112
  c_float    d113;       // Your dual variable for constraint d113
  c_float    d114;       // Your dual variable for constraint d114
  c_float    d115;       // Your dual variable for constraint d115
  c_float    d116;       // Your dual variable for constraint d116
  c_float    d117;       // Your dual variable for constraint d117
  c_float    d118;       // Your dual variable for constraint d118
  c_float    d119;       // Your dual variable for constraint d119
  c_float    d120;       // Your dual variable for constraint d120
  c_float    d121;       // Your dual variable for constraint d121
  c_float    *d122;      // Your dual variable for constraint d122
  c_float    *d123;      // Your dual variable for constraint d123
  c_float    d124;       // Your dual variable for constraint d124
  c_float    d125;       // Your dual variable for constraint d125
  c_float    d126;       // Your dual variable for constraint d126
  c_float    d127;       // Your dual variable for constraint d127
  c_float    d128;       // Your dual variable for constraint d128
  c_float    d129;       // Your dual variable for constraint d129
  c_float    d130;       // Your dual variable for constraint d130
  c_float    d131;       // Your dual variable for constraint d131
  c_float    d132;       // Your dual variable for constraint d132
  c_float    d133;       // Your dual variable for constraint d133
  c_float    d134;       // Your dual variable for constraint d134
  c_float    d135;       // Your dual variable for constraint d135
  c_float    d136;       // Your dual variable for constraint d136
  c_float    d137;       // Your dual variable for constraint d137
  c_float    d138;       // Your dual variable for constraint d138
  c_float    d139;       // Your dual variable for constraint d139
  c_float    d140;       // Your dual variable for constraint d140
  c_float    d141;       // Your dual variable for constraint d141
  c_float    d142;       // Your dual variable for constraint d142
  c_float    d143;       // Your dual variable for constraint d143
  c_float    d144;       // Your dual variable for constraint d144
  c_float    d145;       // Your dual variable for constraint d145
  c_float    d146;       // Your dual variable for constraint d146
  c_float    d147;       // Your dual variable for constraint d147
  c_float    d148;       // Your dual variable for constraint d148
  c_float    d149;       // Your dual variable for constraint d149
  c_float    d150;       // Your dual variable for constraint d150
  c_float    d151;       // Your dual variable for constraint d151
  c_float    *d152;      // Your dual variable for constraint d152
  c_float    *d153;      // Your dual variable for constraint d153
  c_float    d154;       // Your dual variable for constraint d154
  c_float    d155;       // Your dual variable for constraint d155
  c_float    d156;       // Your dual variable for constraint d156
  c_float    d157;       // Your dual variable for constraint d157
  c_float    d158;       // Your dual variable for constraint d158
  c_float    d159;       // Your dual variable for constraint d159
  c_float    d160;       // Your dual variable for constraint d160
  c_float    d161;       // Your dual variable for constraint d161
  c_float    d162;       // Your dual variable for constraint d162
  c_float    d163;       // Your dual variable for constraint d163
  c_float    d164;       // Your dual variable for constraint d164
  c_float    d165;       // Your dual variable for constraint d165
  c_float    d166;       // Your dual variable for constraint d166
  c_float    d167;       // Your dual variable for constraint d167
  c_float    d168;       // Your dual variable for constraint d168
  c_float    d169;       // Your dual variable for constraint d169
  c_float    d170;       // Your dual variable for constraint d170
  c_float    d171;       // Your dual variable for constraint d171
  c_float    d172;       // Your dual variable for constraint d172
  c_float    d173;       // Your dual variable for constraint d173
  c_float    d174;       // Your dual variable for constraint d174
  c_float    d175;       // Your dual variable for constraint d175
  c_float    d176;       // Your dual variable for constraint d176
  c_float    d177;       // Your dual variable for constraint d177
  c_float    d178;       // Your dual variable for constraint d178
  c_float    d179;       // Your dual variable for constraint d179
  c_float    d180;       // Your dual variable for constraint d180
  c_float    d181;       // Your dual variable for constraint d181
  c_float    *d182;      // Your dual variable for constraint d182
  c_float    *d183;      // Your dual variable for constraint d183
  c_float    d184;       // Your dual variable for constraint d184
  c_float    d185;       // Your dual variable for constraint d185
  c_float    d186;       // Your dual variable for constraint d186
  c_float    d187;       // Your dual variable for constraint d187
  c_float    d188;       // Your dual variable for constraint d188
  c_float    d189;       // Your dual variable for constraint d189
  c_float    d190;       // Your dual variable for constraint d190
  c_float    d191;       // Your dual variable for constraint d191
  c_float    d192;       // Your dual variable for constraint d192
  c_float    d193;       // Your dual variable for constraint d193
  c_float    d194;       // Your dual variable for constraint d194
  c_float    d195;       // Your dual variable for constraint d195
  c_float    d196;       // Your dual variable for constraint d196
  c_float    d197;       // Your dual variable for constraint d197
  c_float    d198;       // Your dual variable for constraint d198
  c_float    d199;       // Your dual variable for constraint d199
  c_float    d200;       // Your dual variable for constraint d200
  c_float    d201;       // Your dual variable for constraint d201
  c_float    d202;       // Your dual variable for constraint d202
  c_float    d203;       // Your dual variable for constraint d203
  c_float    d204;       // Your dual variable for constraint d204
  c_float    d205;       // Your dual variable for constraint d205
  c_float    d206;       // Your dual variable for constraint d206
  c_float    d207;       // Your dual variable for constraint d207
  c_float    d208;       // Your dual variable for constraint d208
  c_float    d209;       // Your dual variable for constraint d209
  c_float    d210;       // Your dual variable for constraint d210
  c_float    d211;       // Your dual variable for constraint d211
  c_float    *d212;      // Your dual variable for constraint d212
  c_float    *d213;      // Your dual variable for constraint d213
  c_float    d214;       // Your dual variable for constraint d214
  c_float    d215;       // Your dual variable for constraint d215
  c_float    d216;       // Your dual variable for constraint d216
  c_float    d217;       // Your dual variable for constraint d217
  c_float    d218;       // Your dual variable for constraint d218
  c_float    d219;       // Your dual variable for constraint d219
  c_float    d220;       // Your dual variable for constraint d220
  c_float    d221;       // Your dual variable for constraint d221
  c_float    d222;       // Your dual variable for constraint d222
  c_float    d223;       // Your dual variable for constraint d223
  c_float    d224;       // Your dual variable for constraint d224
  c_float    d225;       // Your dual variable for constraint d225
  c_float    d226;       // Your dual variable for constraint d226
  c_float    d227;       // Your dual variable for constraint d227
  c_float    d228;       // Your dual variable for constraint d228
  c_float    d229;       // Your dual variable for constraint d229
  c_float    d230;       // Your dual variable for constraint d230
  c_float    d231;       // Your dual variable for constraint d231
  c_float    d232;       // Your dual variable for constraint d232
  c_float    d233;       // Your dual variable for constraint d233
  c_float    d234;       // Your dual variable for constraint d234
  c_float    d235;       // Your dual variable for constraint d235
  c_float    d236;       // Your dual variable for constraint d236
  c_float    d237;       // Your dual variable for constraint d237
  c_float    d238;       // Your dual variable for constraint d238
  c_float    d239;       // Your dual variable for constraint d239
  c_float    d240;       // Your dual variable for constraint d240
  c_float    d241;       // Your dual variable for constraint d241
  c_float    *d242;      // Your dual variable for constraint d242
  c_float    *d243;      // Your dual variable for constraint d243
  c_float    d244;       // Your dual variable for constraint d244
  c_float    d245;       // Your dual variable for constraint d245
  c_float    d246;       // Your dual variable for constraint d246
  c_float    d247;       // Your dual variable for constraint d247
  c_float    d248;       // Your dual variable for constraint d248
  c_float    d249;       // Your dual variable for constraint d249
  c_float    d250;       // Your dual variable for constraint d250
  c_float    d251;       // Your dual variable for constraint d251
  c_float    d252;       // Your dual variable for constraint d252
  c_float    d253;       // Your dual variable for constraint d253
  c_float    d254;       // Your dual variable for constraint d254
  c_float    d255;       // Your dual variable for constraint d255
  c_float    d256;       // Your dual variable for constraint d256
  c_float    d257;       // Your dual variable for constraint d257
  c_float    d258;       // Your dual variable for constraint d258
  c_float    d259;       // Your dual variable for constraint d259
  c_float    d260;       // Your dual variable for constraint d260
  c_float    d261;       // Your dual variable for constraint d261
  c_float    d262;       // Your dual variable for constraint d262
  c_float    d263;       // Your dual variable for constraint d263
  c_float    d264;       // Your dual variable for constraint d264
  c_float    d265;       // Your dual variable for constraint d265
  c_float    d266;       // Your dual variable for constraint d266
  c_float    d267;       // Your dual variable for constraint d267
  c_float    d268;       // Your dual variable for constraint d268
  c_float    d269;       // Your dual variable for constraint d269
  c_float    d270;       // Your dual variable for constraint d270
  c_float    d271;       // Your dual variable for constraint d271
  c_float    *d272;      // Your dual variable for constraint d272
  c_float    *d273;      // Your dual variable for constraint d273
  c_float    d274;       // Your dual variable for constraint d274
  c_float    d275;       // Your dual variable for constraint d275
  c_float    d276;       // Your dual variable for constraint d276
  c_float    d277;       // Your dual variable for constraint d277
  c_float    d278;       // Your dual variable for constraint d278
  c_float    d279;       // Your dual variable for constraint d279
  c_float    d280;       // Your dual variable for constraint d280
  c_float    d281;       // Your dual variable for constraint d281
  c_float    d282;       // Your dual variable for constraint d282
  c_float    d283;       // Your dual variable for constraint d283
  c_float    d284;       // Your dual variable for constraint d284
  c_float    d285;       // Your dual variable for constraint d285
  c_float    d286;       // Your dual variable for constraint d286
  c_float    d287;       // Your dual variable for constraint d287
  c_float    d288;       // Your dual variable for constraint d288
  c_float    d289;       // Your dual variable for constraint d289
  c_float    d290;       // Your dual variable for constraint d290
  c_float    d291;       // Your dual variable for constraint d291
  c_float    d292;       // Your dual variable for constraint d292
  c_float    d293;       // Your dual variable for constraint d293
  c_float    d294;       // Your dual variable for constraint d294
  c_float    d295;       // Your dual variable for constraint d295
  c_float    d296;       // Your dual variable for constraint d296
  c_float    d297;       // Your dual variable for constraint d297
  c_float    d298;       // Your dual variable for constraint d298
  c_float    d299;       // Your dual variable for constraint d299
  c_float    d300;       // Your dual variable for constraint d300
  c_float    d301;       // Your dual variable for constraint d301
} CPG_Dual_t;

// Solver information
typedef struct {
  c_float    obj_val;    // Objective function value
  c_int      iter;       // Number of iterations
  char       *status;    // Solver status
  c_float    pri_res;    // Primal residual
  c_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;      // Primal solution
  CPG_Dual_t *dual;      // Dual solution
  CPG_Info_t *info;      // Solver info
} CPG_Result_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern c_float cpg_params_vec[1073];

// Sparse mappings from user-defined to canonical parameters
extern csc canon_A_map;
extern csc canon_l_map;
extern csc canon_u_map;

// Canonical parameters
extern csc canon_P;
extern c_float canon_q[612];
extern csc canon_A;
extern c_float canon_l[772];
extern c_float canon_u[772];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing dual solution
extern CPG_Dual_t CPG_Dual;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;
