
/*
Auto-generated by CVXPYgen on January 30, 2024 at 23:09:57.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static c_int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_X_ref(0, 0.00000000000000000000);
  cpg_update_R(0, 0.10000000000000000555);
  cpg_update_R_grf(0, 0.01000000000000000021);
  cpg_update_x_init(0, 0.00000000000000000000);
  cpg_update_A(0, 1.76405234596766402611);
  cpg_update_no_contact(0, -0.38687084685064654366);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<132; i++) {
    printf("X[%lld] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<60; i++) {
    printf("U[%lld] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<120; i++) {
    printf("F[%lld] = %f\n", i, CPG_Result.prim->F[i]);
  }

  // Print dual solution
  for(i=0; i<12; i++) {
    printf("d0[%lld] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<120; i++) {
    printf("d1[%lld] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<3; i++) {
    printf("d2[%lld] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<3; i++) {
    printf("d3[%lld] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  printf("d4 = %f\n", CPG_Result.dual->d4);
  printf("d5 = %f\n", CPG_Result.dual->d5);
  printf("d6 = %f\n", CPG_Result.dual->d6);
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  printf("d9 = %f\n", CPG_Result.dual->d9);
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  printf("d13 = %f\n", CPG_Result.dual->d13);
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  printf("d17 = %f\n", CPG_Result.dual->d17);
  printf("d18 = %f\n", CPG_Result.dual->d18);
  printf("d19 = %f\n", CPG_Result.dual->d19);
  printf("d20 = %f\n", CPG_Result.dual->d20);
  printf("d21 = %f\n", CPG_Result.dual->d21);
  printf("d22 = %f\n", CPG_Result.dual->d22);
  printf("d23 = %f\n", CPG_Result.dual->d23);
  printf("d24 = %f\n", CPG_Result.dual->d24);
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  printf("d27 = %f\n", CPG_Result.dual->d27);
  printf("d28 = %f\n", CPG_Result.dual->d28);
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  for(i=0; i<3; i++) {
    printf("d32[%lld] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<3; i++) {
    printf("d33[%lld] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  for(i=0; i<3; i++) {
    printf("d62[%lld] = %f\n", i, CPG_Result.dual->d62[i]);
  }
  for(i=0; i<3; i++) {
    printf("d63[%lld] = %f\n", i, CPG_Result.dual->d63[i]);
  }
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  printf("d87 = %f\n", CPG_Result.dual->d87);
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  for(i=0; i<3; i++) {
    printf("d92[%lld] = %f\n", i, CPG_Result.dual->d92[i]);
  }
  for(i=0; i<3; i++) {
    printf("d93[%lld] = %f\n", i, CPG_Result.dual->d93[i]);
  }
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  printf("d99 = %f\n", CPG_Result.dual->d99);
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  for(i=0; i<3; i++) {
    printf("d122[%lld] = %f\n", i, CPG_Result.dual->d122[i]);
  }
  for(i=0; i<3; i++) {
    printf("d123[%lld] = %f\n", i, CPG_Result.dual->d123[i]);
  }
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  printf("d131 = %f\n", CPG_Result.dual->d131);
  printf("d132 = %f\n", CPG_Result.dual->d132);
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);
  printf("d151 = %f\n", CPG_Result.dual->d151);
  for(i=0; i<3; i++) {
    printf("d152[%lld] = %f\n", i, CPG_Result.dual->d152[i]);
  }
  for(i=0; i<3; i++) {
    printf("d153[%lld] = %f\n", i, CPG_Result.dual->d153[i]);
  }
  printf("d154 = %f\n", CPG_Result.dual->d154);
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  printf("d158 = %f\n", CPG_Result.dual->d158);
  printf("d159 = %f\n", CPG_Result.dual->d159);
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  printf("d162 = %f\n", CPG_Result.dual->d162);
  printf("d163 = %f\n", CPG_Result.dual->d163);
  printf("d164 = %f\n", CPG_Result.dual->d164);
  printf("d165 = %f\n", CPG_Result.dual->d165);
  printf("d166 = %f\n", CPG_Result.dual->d166);
  printf("d167 = %f\n", CPG_Result.dual->d167);
  printf("d168 = %f\n", CPG_Result.dual->d168);
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  printf("d171 = %f\n", CPG_Result.dual->d171);
  printf("d172 = %f\n", CPG_Result.dual->d172);
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  printf("d175 = %f\n", CPG_Result.dual->d175);
  printf("d176 = %f\n", CPG_Result.dual->d176);
  printf("d177 = %f\n", CPG_Result.dual->d177);
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  printf("d180 = %f\n", CPG_Result.dual->d180);
  printf("d181 = %f\n", CPG_Result.dual->d181);
  for(i=0; i<3; i++) {
    printf("d182[%lld] = %f\n", i, CPG_Result.dual->d182[i]);
  }
  for(i=0; i<3; i++) {
    printf("d183[%lld] = %f\n", i, CPG_Result.dual->d183[i]);
  }
  printf("d184 = %f\n", CPG_Result.dual->d184);
  printf("d185 = %f\n", CPG_Result.dual->d185);
  printf("d186 = %f\n", CPG_Result.dual->d186);
  printf("d187 = %f\n", CPG_Result.dual->d187);
  printf("d188 = %f\n", CPG_Result.dual->d188);
  printf("d189 = %f\n", CPG_Result.dual->d189);
  printf("d190 = %f\n", CPG_Result.dual->d190);
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  printf("d194 = %f\n", CPG_Result.dual->d194);
  printf("d195 = %f\n", CPG_Result.dual->d195);
  printf("d196 = %f\n", CPG_Result.dual->d196);
  printf("d197 = %f\n", CPG_Result.dual->d197);
  printf("d198 = %f\n", CPG_Result.dual->d198);
  printf("d199 = %f\n", CPG_Result.dual->d199);
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  printf("d203 = %f\n", CPG_Result.dual->d203);
  printf("d204 = %f\n", CPG_Result.dual->d204);
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  printf("d207 = %f\n", CPG_Result.dual->d207);
  printf("d208 = %f\n", CPG_Result.dual->d208);
  printf("d209 = %f\n", CPG_Result.dual->d209);
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  for(i=0; i<3; i++) {
    printf("d212[%lld] = %f\n", i, CPG_Result.dual->d212[i]);
  }
  for(i=0; i<3; i++) {
    printf("d213[%lld] = %f\n", i, CPG_Result.dual->d213[i]);
  }
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);
  printf("d216 = %f\n", CPG_Result.dual->d216);
  printf("d217 = %f\n", CPG_Result.dual->d217);
  printf("d218 = %f\n", CPG_Result.dual->d218);
  printf("d219 = %f\n", CPG_Result.dual->d219);
  printf("d220 = %f\n", CPG_Result.dual->d220);
  printf("d221 = %f\n", CPG_Result.dual->d221);
  printf("d222 = %f\n", CPG_Result.dual->d222);
  printf("d223 = %f\n", CPG_Result.dual->d223);
  printf("d224 = %f\n", CPG_Result.dual->d224);
  printf("d225 = %f\n", CPG_Result.dual->d225);
  printf("d226 = %f\n", CPG_Result.dual->d226);
  printf("d227 = %f\n", CPG_Result.dual->d227);
  printf("d228 = %f\n", CPG_Result.dual->d228);
  printf("d229 = %f\n", CPG_Result.dual->d229);
  printf("d230 = %f\n", CPG_Result.dual->d230);
  printf("d231 = %f\n", CPG_Result.dual->d231);
  printf("d232 = %f\n", CPG_Result.dual->d232);
  printf("d233 = %f\n", CPG_Result.dual->d233);
  printf("d234 = %f\n", CPG_Result.dual->d234);
  printf("d235 = %f\n", CPG_Result.dual->d235);
  printf("d236 = %f\n", CPG_Result.dual->d236);
  printf("d237 = %f\n", CPG_Result.dual->d237);
  printf("d238 = %f\n", CPG_Result.dual->d238);
  printf("d239 = %f\n", CPG_Result.dual->d239);
  printf("d240 = %f\n", CPG_Result.dual->d240);
  printf("d241 = %f\n", CPG_Result.dual->d241);
  for(i=0; i<3; i++) {
    printf("d242[%lld] = %f\n", i, CPG_Result.dual->d242[i]);
  }
  for(i=0; i<3; i++) {
    printf("d243[%lld] = %f\n", i, CPG_Result.dual->d243[i]);
  }
  printf("d244 = %f\n", CPG_Result.dual->d244);
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  printf("d248 = %f\n", CPG_Result.dual->d248);
  printf("d249 = %f\n", CPG_Result.dual->d249);
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  printf("d252 = %f\n", CPG_Result.dual->d252);
  printf("d253 = %f\n", CPG_Result.dual->d253);
  printf("d254 = %f\n", CPG_Result.dual->d254);
  printf("d255 = %f\n", CPG_Result.dual->d255);
  printf("d256 = %f\n", CPG_Result.dual->d256);
  printf("d257 = %f\n", CPG_Result.dual->d257);
  printf("d258 = %f\n", CPG_Result.dual->d258);
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  printf("d261 = %f\n", CPG_Result.dual->d261);
  printf("d262 = %f\n", CPG_Result.dual->d262);
  printf("d263 = %f\n", CPG_Result.dual->d263);
  printf("d264 = %f\n", CPG_Result.dual->d264);
  printf("d265 = %f\n", CPG_Result.dual->d265);
  printf("d266 = %f\n", CPG_Result.dual->d266);
  printf("d267 = %f\n", CPG_Result.dual->d267);
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  printf("d270 = %f\n", CPG_Result.dual->d270);
  printf("d271 = %f\n", CPG_Result.dual->d271);
  for(i=0; i<3; i++) {
    printf("d272[%lld] = %f\n", i, CPG_Result.dual->d272[i]);
  }
  for(i=0; i<3; i++) {
    printf("d273[%lld] = %f\n", i, CPG_Result.dual->d273[i]);
  }
  printf("d274 = %f\n", CPG_Result.dual->d274);
  printf("d275 = %f\n", CPG_Result.dual->d275);
  printf("d276 = %f\n", CPG_Result.dual->d276);
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  printf("d279 = %f\n", CPG_Result.dual->d279);
  printf("d280 = %f\n", CPG_Result.dual->d280);
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  printf("d284 = %f\n", CPG_Result.dual->d284);
  printf("d285 = %f\n", CPG_Result.dual->d285);
  printf("d286 = %f\n", CPG_Result.dual->d286);
  printf("d287 = %f\n", CPG_Result.dual->d287);
  printf("d288 = %f\n", CPG_Result.dual->d288);
  printf("d289 = %f\n", CPG_Result.dual->d289);
  printf("d290 = %f\n", CPG_Result.dual->d290);
  printf("d291 = %f\n", CPG_Result.dual->d291);
  printf("d292 = %f\n", CPG_Result.dual->d292);
  printf("d293 = %f\n", CPG_Result.dual->d293);
  printf("d294 = %f\n", CPG_Result.dual->d294);
  printf("d295 = %f\n", CPG_Result.dual->d295);
  printf("d296 = %f\n", CPG_Result.dual->d296);
  printf("d297 = %f\n", CPG_Result.dual->d297);
  printf("d298 = %f\n", CPG_Result.dual->d298);
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);

  return 0;

}
