
/*
Auto-generated by CVXPYgen on January 26, 2024 at 00:02:18.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"
#include "workspace.h"
#include "osqp.h"

static c_int i;
static c_int j;

// Update user-defined parameters
void cpg_update_X_ref(c_int idx, c_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_R(c_int idx, c_float val){
  cpg_params_vec[idx+120] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_R_grf(c_int idx, c_float val){
  cpg_params_vec[idx+156] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_x_init(c_int idx, c_float val){
  cpg_params_vec[idx+300] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_A(c_int idx, c_float val){
  cpg_params_vec[idx+312] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_no_contact(c_int idx, c_float val){
  cpg_params_vec[idx+1032] = val;
  Canon_Outdated.A = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<3872; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_l(){
  for(i=0; i<532; i++){
    Canon_Params.l[i] = 0;
    for(j=canon_l_map.p[i]; j<canon_l_map.p[i+1]; j++){
      Canon_Params.l[i] += canon_l_map.x[j]*cpg_params_vec[canon_l_map.i[j]];
    }
  }
}

void cpg_canonicalize_u(){
  for(i=0; i<772; i++){
    Canon_Params.u[i] = 0;
    for(j=canon_u_map.p[i]; j<canon_u_map.p[i+1]; j++){
      Canon_Params.u[i] += canon_u_map.x[j]*cpg_params_vec[canon_u_map.i[j]];
    }
  }
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d4 = workspace.solution->y[438];
  CPG_Dual.d5 = workspace.solution->y[532];
  CPG_Dual.d6 = workspace.solution->y[533];
  CPG_Dual.d7 = workspace.solution->y[534];
  CPG_Dual.d8 = workspace.solution->y[535];
  CPG_Dual.d9 = workspace.solution->y[536];
  CPG_Dual.d10 = workspace.solution->y[537];
  CPG_Dual.d11 = workspace.solution->y[439];
  CPG_Dual.d12 = workspace.solution->y[538];
  CPG_Dual.d13 = workspace.solution->y[539];
  CPG_Dual.d14 = workspace.solution->y[540];
  CPG_Dual.d15 = workspace.solution->y[541];
  CPG_Dual.d16 = workspace.solution->y[542];
  CPG_Dual.d17 = workspace.solution->y[543];
  CPG_Dual.d18 = workspace.solution->y[440];
  CPG_Dual.d19 = workspace.solution->y[544];
  CPG_Dual.d20 = workspace.solution->y[545];
  CPG_Dual.d21 = workspace.solution->y[546];
  CPG_Dual.d22 = workspace.solution->y[547];
  CPG_Dual.d23 = workspace.solution->y[548];
  CPG_Dual.d24 = workspace.solution->y[549];
  CPG_Dual.d25 = workspace.solution->y[441];
  CPG_Dual.d26 = workspace.solution->y[550];
  CPG_Dual.d27 = workspace.solution->y[551];
  CPG_Dual.d28 = workspace.solution->y[552];
  CPG_Dual.d29 = workspace.solution->y[553];
  CPG_Dual.d30 = workspace.solution->y[554];
  CPG_Dual.d31 = workspace.solution->y[555];
  CPG_Dual.d34 = workspace.solution->y[448];
  CPG_Dual.d35 = workspace.solution->y[556];
  CPG_Dual.d36 = workspace.solution->y[557];
  CPG_Dual.d37 = workspace.solution->y[558];
  CPG_Dual.d38 = workspace.solution->y[559];
  CPG_Dual.d39 = workspace.solution->y[560];
  CPG_Dual.d40 = workspace.solution->y[561];
  CPG_Dual.d41 = workspace.solution->y[449];
  CPG_Dual.d42 = workspace.solution->y[562];
  CPG_Dual.d43 = workspace.solution->y[563];
  CPG_Dual.d44 = workspace.solution->y[564];
  CPG_Dual.d45 = workspace.solution->y[565];
  CPG_Dual.d46 = workspace.solution->y[566];
  CPG_Dual.d47 = workspace.solution->y[567];
  CPG_Dual.d48 = workspace.solution->y[450];
  CPG_Dual.d49 = workspace.solution->y[568];
  CPG_Dual.d50 = workspace.solution->y[569];
  CPG_Dual.d51 = workspace.solution->y[570];
  CPG_Dual.d52 = workspace.solution->y[571];
  CPG_Dual.d53 = workspace.solution->y[572];
  CPG_Dual.d54 = workspace.solution->y[573];
  CPG_Dual.d55 = workspace.solution->y[451];
  CPG_Dual.d56 = workspace.solution->y[574];
  CPG_Dual.d57 = workspace.solution->y[575];
  CPG_Dual.d58 = workspace.solution->y[576];
  CPG_Dual.d59 = workspace.solution->y[577];
  CPG_Dual.d60 = workspace.solution->y[578];
  CPG_Dual.d61 = workspace.solution->y[579];
  CPG_Dual.d64 = workspace.solution->y[458];
  CPG_Dual.d65 = workspace.solution->y[580];
  CPG_Dual.d66 = workspace.solution->y[581];
  CPG_Dual.d67 = workspace.solution->y[582];
  CPG_Dual.d68 = workspace.solution->y[583];
  CPG_Dual.d69 = workspace.solution->y[584];
  CPG_Dual.d70 = workspace.solution->y[585];
  CPG_Dual.d71 = workspace.solution->y[459];
  CPG_Dual.d72 = workspace.solution->y[586];
  CPG_Dual.d73 = workspace.solution->y[587];
  CPG_Dual.d74 = workspace.solution->y[588];
  CPG_Dual.d75 = workspace.solution->y[589];
  CPG_Dual.d76 = workspace.solution->y[590];
  CPG_Dual.d77 = workspace.solution->y[591];
  CPG_Dual.d78 = workspace.solution->y[460];
  CPG_Dual.d79 = workspace.solution->y[592];
  CPG_Dual.d80 = workspace.solution->y[593];
  CPG_Dual.d81 = workspace.solution->y[594];
  CPG_Dual.d82 = workspace.solution->y[595];
  CPG_Dual.d83 = workspace.solution->y[596];
  CPG_Dual.d84 = workspace.solution->y[597];
  CPG_Dual.d85 = workspace.solution->y[461];
  CPG_Dual.d86 = workspace.solution->y[598];
  CPG_Dual.d87 = workspace.solution->y[599];
  CPG_Dual.d88 = workspace.solution->y[600];
  CPG_Dual.d89 = workspace.solution->y[601];
  CPG_Dual.d90 = workspace.solution->y[602];
  CPG_Dual.d91 = workspace.solution->y[603];
  CPG_Dual.d94 = workspace.solution->y[468];
  CPG_Dual.d95 = workspace.solution->y[604];
  CPG_Dual.d96 = workspace.solution->y[605];
  CPG_Dual.d97 = workspace.solution->y[606];
  CPG_Dual.d98 = workspace.solution->y[607];
  CPG_Dual.d99 = workspace.solution->y[608];
  CPG_Dual.d100 = workspace.solution->y[609];
  CPG_Dual.d101 = workspace.solution->y[469];
  CPG_Dual.d102 = workspace.solution->y[610];
  CPG_Dual.d103 = workspace.solution->y[611];
  CPG_Dual.d104 = workspace.solution->y[612];
  CPG_Dual.d105 = workspace.solution->y[613];
  CPG_Dual.d106 = workspace.solution->y[614];
  CPG_Dual.d107 = workspace.solution->y[615];
  CPG_Dual.d108 = workspace.solution->y[470];
  CPG_Dual.d109 = workspace.solution->y[616];
  CPG_Dual.d110 = workspace.solution->y[617];
  CPG_Dual.d111 = workspace.solution->y[618];
  CPG_Dual.d112 = workspace.solution->y[619];
  CPG_Dual.d113 = workspace.solution->y[620];
  CPG_Dual.d114 = workspace.solution->y[621];
  CPG_Dual.d115 = workspace.solution->y[471];
  CPG_Dual.d116 = workspace.solution->y[622];
  CPG_Dual.d117 = workspace.solution->y[623];
  CPG_Dual.d118 = workspace.solution->y[624];
  CPG_Dual.d119 = workspace.solution->y[625];
  CPG_Dual.d120 = workspace.solution->y[626];
  CPG_Dual.d121 = workspace.solution->y[627];
  CPG_Dual.d124 = workspace.solution->y[478];
  CPG_Dual.d125 = workspace.solution->y[628];
  CPG_Dual.d126 = workspace.solution->y[629];
  CPG_Dual.d127 = workspace.solution->y[630];
  CPG_Dual.d128 = workspace.solution->y[631];
  CPG_Dual.d129 = workspace.solution->y[632];
  CPG_Dual.d130 = workspace.solution->y[633];
  CPG_Dual.d131 = workspace.solution->y[479];
  CPG_Dual.d132 = workspace.solution->y[634];
  CPG_Dual.d133 = workspace.solution->y[635];
  CPG_Dual.d134 = workspace.solution->y[636];
  CPG_Dual.d135 = workspace.solution->y[637];
  CPG_Dual.d136 = workspace.solution->y[638];
  CPG_Dual.d137 = workspace.solution->y[639];
  CPG_Dual.d138 = workspace.solution->y[480];
  CPG_Dual.d139 = workspace.solution->y[640];
  CPG_Dual.d140 = workspace.solution->y[641];
  CPG_Dual.d141 = workspace.solution->y[642];
  CPG_Dual.d142 = workspace.solution->y[643];
  CPG_Dual.d143 = workspace.solution->y[644];
  CPG_Dual.d144 = workspace.solution->y[645];
  CPG_Dual.d145 = workspace.solution->y[481];
  CPG_Dual.d146 = workspace.solution->y[646];
  CPG_Dual.d147 = workspace.solution->y[647];
  CPG_Dual.d148 = workspace.solution->y[648];
  CPG_Dual.d149 = workspace.solution->y[649];
  CPG_Dual.d150 = workspace.solution->y[650];
  CPG_Dual.d151 = workspace.solution->y[651];
  CPG_Dual.d154 = workspace.solution->y[488];
  CPG_Dual.d155 = workspace.solution->y[652];
  CPG_Dual.d156 = workspace.solution->y[653];
  CPG_Dual.d157 = workspace.solution->y[654];
  CPG_Dual.d158 = workspace.solution->y[655];
  CPG_Dual.d159 = workspace.solution->y[656];
  CPG_Dual.d160 = workspace.solution->y[657];
  CPG_Dual.d161 = workspace.solution->y[489];
  CPG_Dual.d162 = workspace.solution->y[658];
  CPG_Dual.d163 = workspace.solution->y[659];
  CPG_Dual.d164 = workspace.solution->y[660];
  CPG_Dual.d165 = workspace.solution->y[661];
  CPG_Dual.d166 = workspace.solution->y[662];
  CPG_Dual.d167 = workspace.solution->y[663];
  CPG_Dual.d168 = workspace.solution->y[490];
  CPG_Dual.d169 = workspace.solution->y[664];
  CPG_Dual.d170 = workspace.solution->y[665];
  CPG_Dual.d171 = workspace.solution->y[666];
  CPG_Dual.d172 = workspace.solution->y[667];
  CPG_Dual.d173 = workspace.solution->y[668];
  CPG_Dual.d174 = workspace.solution->y[669];
  CPG_Dual.d175 = workspace.solution->y[491];
  CPG_Dual.d176 = workspace.solution->y[670];
  CPG_Dual.d177 = workspace.solution->y[671];
  CPG_Dual.d178 = workspace.solution->y[672];
  CPG_Dual.d179 = workspace.solution->y[673];
  CPG_Dual.d180 = workspace.solution->y[674];
  CPG_Dual.d181 = workspace.solution->y[675];
  CPG_Dual.d184 = workspace.solution->y[498];
  CPG_Dual.d185 = workspace.solution->y[676];
  CPG_Dual.d186 = workspace.solution->y[677];
  CPG_Dual.d187 = workspace.solution->y[678];
  CPG_Dual.d188 = workspace.solution->y[679];
  CPG_Dual.d189 = workspace.solution->y[680];
  CPG_Dual.d190 = workspace.solution->y[681];
  CPG_Dual.d191 = workspace.solution->y[499];
  CPG_Dual.d192 = workspace.solution->y[682];
  CPG_Dual.d193 = workspace.solution->y[683];
  CPG_Dual.d194 = workspace.solution->y[684];
  CPG_Dual.d195 = workspace.solution->y[685];
  CPG_Dual.d196 = workspace.solution->y[686];
  CPG_Dual.d197 = workspace.solution->y[687];
  CPG_Dual.d198 = workspace.solution->y[500];
  CPG_Dual.d199 = workspace.solution->y[688];
  CPG_Dual.d200 = workspace.solution->y[689];
  CPG_Dual.d201 = workspace.solution->y[690];
  CPG_Dual.d202 = workspace.solution->y[691];
  CPG_Dual.d203 = workspace.solution->y[692];
  CPG_Dual.d204 = workspace.solution->y[693];
  CPG_Dual.d205 = workspace.solution->y[501];
  CPG_Dual.d206 = workspace.solution->y[694];
  CPG_Dual.d207 = workspace.solution->y[695];
  CPG_Dual.d208 = workspace.solution->y[696];
  CPG_Dual.d209 = workspace.solution->y[697];
  CPG_Dual.d210 = workspace.solution->y[698];
  CPG_Dual.d211 = workspace.solution->y[699];
  CPG_Dual.d214 = workspace.solution->y[508];
  CPG_Dual.d215 = workspace.solution->y[700];
  CPG_Dual.d216 = workspace.solution->y[701];
  CPG_Dual.d217 = workspace.solution->y[702];
  CPG_Dual.d218 = workspace.solution->y[703];
  CPG_Dual.d219 = workspace.solution->y[704];
  CPG_Dual.d220 = workspace.solution->y[705];
  CPG_Dual.d221 = workspace.solution->y[509];
  CPG_Dual.d222 = workspace.solution->y[706];
  CPG_Dual.d223 = workspace.solution->y[707];
  CPG_Dual.d224 = workspace.solution->y[708];
  CPG_Dual.d225 = workspace.solution->y[709];
  CPG_Dual.d226 = workspace.solution->y[710];
  CPG_Dual.d227 = workspace.solution->y[711];
  CPG_Dual.d228 = workspace.solution->y[510];
  CPG_Dual.d229 = workspace.solution->y[712];
  CPG_Dual.d230 = workspace.solution->y[713];
  CPG_Dual.d231 = workspace.solution->y[714];
  CPG_Dual.d232 = workspace.solution->y[715];
  CPG_Dual.d233 = workspace.solution->y[716];
  CPG_Dual.d234 = workspace.solution->y[717];
  CPG_Dual.d235 = workspace.solution->y[511];
  CPG_Dual.d236 = workspace.solution->y[718];
  CPG_Dual.d237 = workspace.solution->y[719];
  CPG_Dual.d238 = workspace.solution->y[720];
  CPG_Dual.d239 = workspace.solution->y[721];
  CPG_Dual.d240 = workspace.solution->y[722];
  CPG_Dual.d241 = workspace.solution->y[723];
  CPG_Dual.d244 = workspace.solution->y[518];
  CPG_Dual.d245 = workspace.solution->y[724];
  CPG_Dual.d246 = workspace.solution->y[725];
  CPG_Dual.d247 = workspace.solution->y[726];
  CPG_Dual.d248 = workspace.solution->y[727];
  CPG_Dual.d249 = workspace.solution->y[728];
  CPG_Dual.d250 = workspace.solution->y[729];
  CPG_Dual.d251 = workspace.solution->y[519];
  CPG_Dual.d252 = workspace.solution->y[730];
  CPG_Dual.d253 = workspace.solution->y[731];
  CPG_Dual.d254 = workspace.solution->y[732];
  CPG_Dual.d255 = workspace.solution->y[733];
  CPG_Dual.d256 = workspace.solution->y[734];
  CPG_Dual.d257 = workspace.solution->y[735];
  CPG_Dual.d258 = workspace.solution->y[520];
  CPG_Dual.d259 = workspace.solution->y[736];
  CPG_Dual.d260 = workspace.solution->y[737];
  CPG_Dual.d261 = workspace.solution->y[738];
  CPG_Dual.d262 = workspace.solution->y[739];
  CPG_Dual.d263 = workspace.solution->y[740];
  CPG_Dual.d264 = workspace.solution->y[741];
  CPG_Dual.d265 = workspace.solution->y[521];
  CPG_Dual.d266 = workspace.solution->y[742];
  CPG_Dual.d267 = workspace.solution->y[743];
  CPG_Dual.d268 = workspace.solution->y[744];
  CPG_Dual.d269 = workspace.solution->y[745];
  CPG_Dual.d270 = workspace.solution->y[746];
  CPG_Dual.d271 = workspace.solution->y[747];
  CPG_Dual.d274 = workspace.solution->y[528];
  CPG_Dual.d275 = workspace.solution->y[748];
  CPG_Dual.d276 = workspace.solution->y[749];
  CPG_Dual.d277 = workspace.solution->y[750];
  CPG_Dual.d278 = workspace.solution->y[751];
  CPG_Dual.d279 = workspace.solution->y[752];
  CPG_Dual.d280 = workspace.solution->y[753];
  CPG_Dual.d281 = workspace.solution->y[529];
  CPG_Dual.d282 = workspace.solution->y[754];
  CPG_Dual.d283 = workspace.solution->y[755];
  CPG_Dual.d284 = workspace.solution->y[756];
  CPG_Dual.d285 = workspace.solution->y[757];
  CPG_Dual.d286 = workspace.solution->y[758];
  CPG_Dual.d287 = workspace.solution->y[759];
  CPG_Dual.d288 = workspace.solution->y[530];
  CPG_Dual.d289 = workspace.solution->y[760];
  CPG_Dual.d290 = workspace.solution->y[761];
  CPG_Dual.d291 = workspace.solution->y[762];
  CPG_Dual.d292 = workspace.solution->y[763];
  CPG_Dual.d293 = workspace.solution->y[764];
  CPG_Dual.d294 = workspace.solution->y[765];
  CPG_Dual.d295 = workspace.solution->y[531];
  CPG_Dual.d296 = workspace.solution->y[766];
  CPG_Dual.d297 = workspace.solution->y[767];
  CPG_Dual.d298 = workspace.solution->y[768];
  CPG_Dual.d299 = workspace.solution->y[769];
  CPG_Dual.d300 = workspace.solution->y[770];
  CPG_Dual.d301 = workspace.solution->y[771];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = workspace.info->obj_val;
  CPG_Info.iter = workspace.info->iter;
  CPG_Info.status = workspace.info->status;
  CPG_Info.pri_res = workspace.info->pri_res;
  CPG_Info.dua_res = workspace.info->dua_res;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
    osqp_update_A(&workspace, Canon_Params.A->x, 0, 0);
  }
  if (Canon_Outdated.l && Canon_Outdated.u) {
    cpg_canonicalize_l();
    cpg_canonicalize_u();
    osqp_update_bounds(&workspace, Canon_Params.l, Canon_Params.u);
  } else if (Canon_Outdated.l) {
    cpg_canonicalize_l();
    osqp_update_lower_bound(&workspace, Canon_Params.l);
  } else if (Canon_Outdated.u) {
    cpg_canonicalize_u();
    osqp_update_upper_bound(&workspace, Canon_Params.u);
  }
  // Solve with OSQP
  osqp_solve(&workspace);
  // Retrieve results
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.q = 0;
  Canon_Outdated.d = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.l = 0;
  Canon_Outdated.u = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  osqp_set_default_settings(&settings);
}

void cpg_set_solver_rho(c_float rho_new){
  osqp_update_rho(&workspace, rho_new);
}

void cpg_set_solver_max_iter(c_int max_iter_new){
  osqp_update_max_iter(&workspace, max_iter_new);
}

void cpg_set_solver_eps_abs(c_float eps_abs_new){
  osqp_update_eps_abs(&workspace, eps_abs_new);
}

void cpg_set_solver_eps_rel(c_float eps_rel_new){
  osqp_update_eps_rel(&workspace, eps_rel_new);
}

void cpg_set_solver_eps_prim_inf(c_float eps_prim_inf_new){
  osqp_update_eps_prim_inf(&workspace, eps_prim_inf_new);
}

void cpg_set_solver_eps_dual_inf(c_float eps_dual_inf_new){
  osqp_update_eps_dual_inf(&workspace, eps_dual_inf_new);
}

void cpg_set_solver_alpha(c_float alpha_new){
  osqp_update_alpha(&workspace, alpha_new);
}

void cpg_set_solver_scaled_termination(c_int scaled_termination_new){
  osqp_update_scaled_termination(&workspace, scaled_termination_new);
}

void cpg_set_solver_check_termination(c_int check_termination_new){
  osqp_update_check_termination(&workspace, check_termination_new);
}

void cpg_set_solver_warm_start(c_int warm_start_new){
  osqp_update_warm_start(&workspace, warm_start_new);
}
